### ISSUE TITLE
Claims - Add ClaimType to GetClaims Response to Indicate Optional Payment Claims

### ISSUE THREAD

**Issue by thebingi** [stadlar/IST-FUT-FMTH#180]
Title: Add ClaimType to GetClaims Response to Indicate Optional Payment Claims

Description:

I propose adding a new property, "ClaimType," to the response object for the GetClaims operation to indicate whether the claims are optional payment claims. In the current system, the following types are available:

- `NormalClaim`: A regular claim.
- `OptionalPaymentClaim`: An optional payment claim.
- `RefundClaim`: A refund claim.
- `BalanceClaim`: A government balance claim (only for government entities).

Suggested addition to the schema:

```yaml
claimType:
  description: Claim type
  type: string
  enum:
    - "NormalClaim"
    - "OptionalPaymentClaim"
    - "RefundClaim"
    - "BalanceClaim"
```

By adding this new property, we can provide clearer information on the claim types and make it easier to distinguish between different types of claims in the GetClaims response.
