### ISSUE TITLE
Claims - printingLocation

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#70]
```
    printingLocation:
      description: Printing place information
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
```

What is this? What purpose does this have? How is this to be used? This is only relevant for those banks which use RB for printing so remove or make optional.
